### ISSUE TITLE
XNA Game Studio content

### ISSUE THREAD

**Issue by walbourn** [tomizechsterson/game-state-management-monogame#1]
Most of the XNA Game Studio education content is no longer hosted on Microsoft servers.  I've been referencing this GitHub which is a fairly complete archive

https://github.com/SimonDarksideJ/XNAGameStudio/wiki

**Comment by tomizechsterson** [comment]
Nice! I'll update the readme here to make a note of it. Thank you for the heads up; that's a pretty comprehensive archive!

**Comment by tomizechsterson** [comment]
Just realized I never closed this after updating the readme. Thanks again for the tip!
